In [1]:
import pandas as pd
import numpy as np

df= pd.read_csv(r'C:\ProgramData\MySQL\MySQL Server 8.0\Uploads\customer_behavior.csv', on_bad_lines='skip')

In [2]:
df.head()

,Customer ID,Purchase_Date,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,04-02-2024,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,24-12-2022,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,08-04-2023,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,05-03-2023,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,22-04-2022,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
df.shape

(3900, 19)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Purchase_Date           3900 non-null   str
 2   Age                     3900 non-null   int64
 3   Gender                  3900 non-null   str
 4   Item Purchased          3900 non-null   str
 5   Category                3900 non-null   str
 6   Purchase Amount (USD)   3900 non-null   int64
 7   Location                3900 non-null   str
 8   Size                    3900 non-null   str
 9   Color                   3900 non-null   str
 10  Season                  3900 non-null   str
 11  Review Rating           3863 non-null   float64
 12  Subscription Status     3900 non-null   str
 13  Shipping Type           3900 non-null   str
 14  Discount Applied        3900 non-null   str
 15  Promo Code Used         3900 non-null   str
 16  Previous Purchases      3900 non-null   int64
 17  Payment Method          3900 non-null   str
 18  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(14)
memory usage: 579.0 KB

In [5]:
#df.describe(include='all')
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [6]:
# convert to datetime
df['Purchase_Date'] = pd.to_datetime(df['Purchase_Date'], format='%d-%m-%Y')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Purchase_Date           3900 non-null   datetime64[us]
 2   Age                     3900 non-null   int64
 3   Gender                  3900 non-null   str
 4   Item Purchased          3900 non-null   str
 5   Category                3900 non-null   str
 6   Purchase Amount (USD)   3900 non-null   int64
 7   Location                3900 non-null   str
 8   Size                    3900 non-null   str
 9   Color                   3900 non-null   str
 10  Season                  3900 non-null   str
 11  Review Rating           3863 non-null   float64
 12  Subscription Status     3900 non-null   str
 13  Shipping Type           3900 non-null   str
 14  Discount Applied        3900 non-null   str
 15  Promo Code Used         3900 non-null   str
 16  Previous Purchases      3900 non-null   int64
 17  Payment Method          3900 non-null   str
 18  Frequency of Purchases  3900 non-null   str
dtypes: datetime64[us](1), float64(1), int64(4), str(13)
memory usage: 579.0 KB

In [8]:
df.isnull().sum()

Customer ID                0
Purchase_Date              0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [9]:
# Imputing missing values in review ratings column and  transforming into median values by category
df['Review Rating']= df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [10]:
df.isnull().sum()

Customer ID               0
Purchase_Date             0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [11]:
# renaming columns according to snake casing for better readability and documentation
df.columns = df.columns.str.strip()   # remove extra spaces from start/end
df.columns = df.columns.str.lower()   # lowercase
df.columns = df.columns.str.replace(' ', '_') 
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})


# df.columns = (
#    df.columns
#   .str.strip()
#   .str.lower()
#   .str.replace(r'\s+', '_', regex=True))

In [12]:
df.columns

Index(['customer_id', 'purchase_date', 'age', 'gender', 'item_purchased',
       'category', 'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [13]:
# create new age column
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_groups']= pd.qcut(df['age'], q=4, labels = labels)



# bins = [18, 30, 45, 60, 100]
# labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
# df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels)

In [14]:
df[['age', 'age_groups']].head(10)

   age   age_groups
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [15]:
# create new column purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [16]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [17]:
# checks whether discount_applied and promo_code_used are identical for every row.

(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [18]:
# dropping promo code used column.

df= df.drop('promo_code_used', axis =1)

In [19]:
 
df['purchase_year']     = df['purchase_date'].dt.year
# → gives: 2022, 2023, 2024
 
df['purchase_month']    = df['purchase_date'].dt.month
# → gives: 1, 2, 3, ... 12  (as integers)
 
df['purchase_month_name'] = df['purchase_date'].dt.strftime('%b')
# → gives: 'Jan', 'Feb', 'Mar' ... 'Dec'  (short text names)
 
df['purchase_quarter']  = df['purchase_date'].dt.quarter
# → gives: 1, 2, 3, or 4  (Q1 = Jan-Mar, Q2 = Apr-Jun...)
 
df['purchase_week']     = df['purchase_date'].dt.isocalendar().week.astype(int)
# → gives: 1-52  (week number of the year)
 
df['purchase_day_name'] = df['purchase_date'].dt.day_name()
# → gives: 'Monday', 'Tuesday' ... 'Sunday'
 
df['is_weekend']        = df['purchase_day_name'].isin(['Saturday','Sunday'])
# → gives: True or False  (useful for weekend vs weekday analysis)

In [20]:
df.columns

Index(['customer_id', 'purchase_date', 'age', 'gender', 'item_purchased',
       'category', 'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_groups', 'purchase_frequency_days',
       'purchase_year', 'purchase_month', 'purchase_month_name',
       'purchase_quarter', 'purchase_week', 'purchase_day_name', 'is_weekend'],
      dtype='str')

In [21]:
# Review all new columns 
df.head(5)

,customer_id,purchase_date,age,gender,item_purchased,category,purchase_amount,location,size,color,...,frequency_of_purchases,age_groups,purchase_frequency_days,purchase_year,purchase_month,purchase_month_name,purchase_quarter,purchase_week,purchase_day_name,is_weekend
0,1,2024-02-04,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,...,Fortnightly,Middle-aged,14,2024,2,Feb,1,5,Sunday,True
1,2,2022-12-24,19,Male,Sweater,Clothing,64,Maine,L,Maroon,...,Fortnightly,Young Adult,14,2022,12,Dec,4,51,Saturday,True
2,3,2023-04-08,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,...,Weekly,Middle-aged,7,2023,4,Apr,2,14,Saturday,True
3,4,2023-03-05,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,...,Weekly,Young Adult,7,2023,3,Mar,1,9,Sunday,True
4,5,2022-04-22,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,...,Annually,Middle-aged,365,2022,4,Apr,2,16,Friday,False

In [22]:
# Define which months belong to each season
season_month_map = {
    'Winter': [12, 1, 2],
    'Spring': [3, 4, 5],
    'Summer': [6, 7, 8],
    'Fall':   [9, 10, 11]
}

In [23]:
# Create a helper function that returns True if date matches season
df['season_date_match']= df.apply(
    lambda row: row['purchase_month'] in season_month_map.get(row['season'] , []), axis=1)

In [24]:
# Count mismatches
mismatches = df[~df['season_date_match']]
print(f'Total mismatches: {len(mismatches)}')

Total mismatches: 0

In [25]:
# Drop the helper column (no longer needed)
df = df.drop('season_date_match', axis=1)

In [26]:
# Days since last purchases (Recency)

reference_date= df['purchase_date'].max()
df['days_since_purchase']= (reference_date - df['purchase_date']).dt.days

In [27]:
# Spend Segment (Customer grouping)

df['spend_segment'] = pd.cut(
    df['purchase_amount'],
    bins=[0, 30, 60, 80, 100],
    labels=['Low ($0-30)', 'Medium ($31-60)', 'High ($61-80)', 'Premium ($81-100)']
)

In [28]:
# Estimated Purchase per year

df['est_purchases_per_year']=(365/df['purchase_frequency_days']).round(1)

In [29]:
# Estimated Annual Value

df['estimated_annual_value'] = (
    df['purchase_amount'] * df['est_purchases_per_year']
).round(2)

In [30]:
# Check results

df[['purchase_date','days_since_purchase','spend_segment',
    'est_purchases_per_year','estimated_annual_value']].head(5)

,purchase_date,days_since_purchase,spend_segment,est_purchases_per_year,estimated_annual_value
0,2024-02-04,300,Medium ($31-60),26.1,1383.3
1,2022-12-24,707,High ($61-80),26.1,1670.4
2,2023-04-08,602,High ($61-80),52.1,3803.3
3,2023-03-05,636,Premium ($81-100),52.1,4689.0
4,2022-04-22,953,Medium ($31-60),1.0,49.0

### Connecting Python Script to MYSQL

In [31]:
!pip install pymysql sqlalchemy

'C:\Program Files\Python314\Scripts\pip.exe' was blocked by your organization's Device Guard policy.
Contact your support person for more info.

In [32]:
from sqlalchemy import create_engine

# MySQL connection
username = "root"
password = "sql123"
host = "localhost"
port = "3306"
database = "customer_behavior"

engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}')

# Write DataFrame to MySQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)

,customer_id,purchase_date,age,gender,item_purchased,category,purchase_amount,location,size,color,...,purchase_month,purchase_month_name,purchase_quarter,purchase_week,purchase_day_name,is_weekend,days_since_purchase,spend_segment,est_purchases_per_year,estimated_annual_value
0,1,2024-02-04,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,...,2,Feb,1,5,Sunday,1,300,Medium ($31-60),26.1,1383.3
1,2,2022-12-24,19,Male,Sweater,Clothing,64,Maine,L,Maroon,...,12,Dec,4,51,Saturday,1,707,High ($61-80),26.1,1670.4
2,3,2023-04-08,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,...,4,Apr,2,14,Saturday,1,602,High ($61-80),52.1,3803.3
3,4,2023-03-05,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,...,3,Mar,1,9,Sunday,1,636,Premium ($81-100),52.1,4689.0
4,5,2022-04-22,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,...,4,Apr,2,16,Friday,0,953,Medium ($31-60),1.0,49.0